#!/bin/bash

emacsclient --socket-name=emacs-gui --no-wait --eval "(if (> (length (frame-list)) 1) 't)" | grep t

if [ "$?" = "1" ]; then
    if [ "$DISPLAY" = "" ]; then
        emacsclient --socket-name=emacs-gui --create-frame --alternate-editor="" "$@"
    else
        emacsclient --socket-name=emacs-gui --create-frame --no-wait --alternate-editor="" "$@"
    fi
else
    if [ "$DISPLAY" = "" ]; then
        emacsclient--socket-name=emacs-gui --alternate-editor="" "$@"
    else
        emacsclient --socket-name=emacs-gui --no-wait --alternate-editor="" "$@"
    fi
fi
i3-msg "[title=term-ranger]" move scratchpad &>/dev/null
i3-msg "[title=term-up]" move scratchpad &>/dev/null
# i3-msg "[class=Emacs]" focus &>/dev/null
