#!/usr/bin/env bash

git -C /home/jerry/creative add -A
git -C /home/jerry/creative commit -am "auto-commit"
git -C /home/jerry/creative push

git -C /home/jerry/org add -A
git -C /home/jerry/org commit -am "auto-commit"
git -C /home/jerry/org push
