#!/usr/bin/env python3

import os
import sys

os.system("clear")
sys.tracebacklimit = 0

command = "play --no-show-progress"
alert_sound = '"$HOME"/Sounds/apple.mp3'
time = input("\n 1. Please type in seconds the time desired to be alerted:\n ")

print(f"\n 2. You will be alerted in {time} seconds\n ")
os.system(f"sleep {time} && {command} {alert_sound}")
print(f" 3. You have been alerted. Goodbye!\n ")
