#!/usr/bin/env bash

clear

# system upgrade
sudo apt -y update
apt -y dist-upgrade

# system packages
sudo apt -y install i3 i3status i3lock i3blocks rofi neovim           \
lxappearance calibre zathura zathura-pdf-poppler qbittorrent uget     \
xclip dmenu unclutter trash-cli arandr xbindkeys font-manager atool   \
silversearcher-ag clang aspell-pt-br pandoc markdown xsel xdotool     \
zenity lxde-settings-daemon w3m-img gcc-multilib make build-essential  \
python-all python-pip python3-pip  python-wheel python3-wheel          \
python-setuptools python3-setuptools wget curl cmus cmus-plugin-ffmpeg \
libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm   \
libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev            \
liblzma-dev python-openssl git keepassxc gnome-disk-utility zenity     \
libffi-dev wordnet simplescreenrecorder okular okular-extra-backends   \
mercurial ninja-build gettext libtool libtool-bin autoconf automake    \
cmake g++ pkg-config unzip gcc-multilib g++-multilib                   \
baobab xorg-dev xcape fasd rubygems mpv feh rar nscd

# pyenv dependencies
sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev  \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

# pyenv install
pip install --upgrade pip
curl https://pyenv.run | bash

# flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# clean
sudo apt -y autoremove
sudo apt -y autoclean
