#!/usr/bin/env bash

clear
sudo apt-get install scrot python3-tk python3-dev &&
# pip install --upgrade pip &&
# pyenv install 3.8.0 &&
# pyenv global 3.8.0 &&
pip install termdown ranger python3-xlib pyautogui
