#!/usr/bin/env python3


import os
import sys
import argparse

os.system("clear")
sys.tracebacklimit = 0

parser = argparse.ArgumentParser()

parser.add_argument("x", type=int, help="the base")

parser.add_argument("y", type=int, help="the exponent")

parser.add_argument("-v", "--verbosity", action="count", default=0)

args = parser.parse_args()

answer = args.x ** args.y

if args.verbosity >= 2:
    print(f"\n {args.x} to the power {args.y} equals to {answer}")
elif args.verbosity >= 1:
    print(f"\n {args.x}^{args.y} == {answer}")
else:
    print(answer)
