#!/usr/bin/env bash

message="Add or refresh gitignore"

clear &&
echo ""

echo "adding gitignore" &&
git add .gitignore -f &&

echo "commiting" &&
git commit -m "$message" &&

echo "pushing" &&
git push
