#!/bin/bash

clear
echo ""
echo " #adding all files#"
echo ""
git add -A
echo ""
echo " #commiting"#
echo ""
git commit -am " Automatic commit"
echo ""
echo " #push force#"
echo ""
git push
echo ""
echo " #finished#"
echo ""
