#!/usr/bin/env bash

sudo apt install -y python-all python-pip python3-pip python-wheel python3-wheel python-setuptools python3-setuptools libffi-dev make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
