#!/usr/bin/env bash

# run this on the directory where you want to save
# git clone git://git.savannah.gnu.org/emacs.git . &&
# ./autogen.sh &&
./configure --prefix="$HOME"/maps/emacs_mini --without-all --without-x CFLAGS='-Os -m32' &&
make &&
sudo make install
